alter table public.access_grants
  add column if not exists last_seen_at timestamptz;

create table if not exists public.access_events (
  id bigint generated by default as identity primary key,
  access_email text not null,
  action text not null,
  days_delta integer not null default 0,
  performed_by text,
  created_at timestamptz not null default now()
);

alter table public.access_events enable row level security;

drop policy if exists master_read_access_events on public.access_events;
create policy master_read_access_events on public.access_events
  for select to authenticated
  using (public.is_aula_clara_master());

drop policy if exists master_insert_access_events on public.access_events;
create policy master_insert_access_events on public.access_events
  for insert to authenticated
  with check (public.is_aula_clara_master());

grant select, insert on public.access_events to authenticated;
grant usage, select on sequence public.access_events_id_seq to authenticated;

create or replace function public.set_access_event_actor()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.performed_by := lower(coalesce((select auth.jwt() ->> 'email'), ''));
  return new;
end;
$$;

drop trigger if exists set_access_event_actor on public.access_events;
create trigger set_access_event_actor
before insert on public.access_events
for each row execute function public.set_access_event_actor();

create or replace function public.touch_current_access()
returns void
language sql
security definer
set search_path = ''
as $$
  update public.access_grants
     set last_seen_at = now(), updated_at = now()
   where lower(email) = lower(coalesce((select auth.jwt() ->> 'email'), ''));
$$;

revoke all on function public.touch_current_access() from public;
revoke all on function public.touch_current_access() from anon;
grant execute on function public.touch_current_access() to authenticated;
